# SPDX-FileCopyrightText: 2020 2019-2020 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

CAPABILITIES_ENDPOINT = '/capabilities'
CLIENT_ENDPOINT = '/clients'
CLIENT_MAPPING_ENDPOINT = '/identifier'
DATA_ENDPOINT = '/data'
DATA_ASYNC_ENDPOINT = DATA_ENDPOINT + '/jobs'
DATA_ID_ENDPOINT = DATA_ASYNC_ENDPOINT + '/{id}'
DATA_ACTIVATION_ASYNC_ENDPOINT = DATA_ENDPOINT + '/activation'
DATA_ACTIVATION_ID_ENDPOINT = DATA_ACTIVATION_ASYNC_ENDPOINT + '/{id}'
DOCUMENT_ENDPOINT = '/document/jobs'
DOCUMENT_ID_ENDPOINT = DOCUMENT_ENDPOINT + '/{document_id}'
DOCUMENT_CONFIRM_ENDPOINT = DOCUMENT_ID_ENDPOINT + '/confirm'
DOCUMENT_PAGES_ENDPOINT = DOCUMENT_ID_ENDPOINT + '/pages'
DOCUMENT_PAGE_ENDPOINT = DOCUMENT_PAGES_ENDPOINT + '/{page_number}'
DOCUMENT_PAGES_TEXT_ENDPOINT = DOCUMENT_PAGES_ENDPOINT + '/text'
DOCUMENT_PAGE_TEXT_ENDPOINT = DOCUMENT_PAGE_ENDPOINT + '/text'
DOCUMENT_PAGES_DIMENSIONS_ENDPOINT = DOCUMENT_PAGES_ENDPOINT + '/dimensions'
DOCUMENT_PAGE_DIMENSIONS_ENDPOINT = DOCUMENT_PAGE_ENDPOINT + '/dimensions'
DOCUMENT_ID_REQUEST_ENDPOINT = DOCUMENT_ID_ENDPOINT + '/request'
