# SPDX-FileCopyrightText: 2020 2019-2020 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

API_STATUS_FIELD = 'status'

STR_STATUS_CONFIRMED = 'CONFIRMED'
STR_STATUS_DONE = 'DONE'
STR_STATUS_FAILED = 'FAILED'
STR_STATUS_PENDING = 'PENDING'
STR_STATUS_SUCCESS = 'SUCCESS'
STR_STATUS_SUCCEEDED = 'SUCCEEDED'
SUCCEEDED_STATUSES = {STR_STATUS_CONFIRMED, STR_STATUS_DONE, STR_STATUS_SUCCESS, STR_STATUS_SUCCEEDED}
FAILED_STATUSES = {STR_STATUS_FAILED}


MIN_POLLING_INTERVAL = 0.2

